### ISSUE TITLE
cHALS loss does not monotonically decrease

### ISSUE THREAD

**Issue by bantin** [degleris1/cmfpy#16]
I looked pretty carefully through the cHALS update code, and couldn't find any glaring errors. The next suspect might be the way which we calculate the loss at each iteration, or the way we update the residual. @degleris1

**Comment by degleris1** [comment]
Got it!
- The `H` update was not calculating norms properly, since it failed to account for the trimming of `W_k` towards the end.
- The `W` update's did not calculate `ind` correctly, which stacks shifted versions of `H` (as opposed to shifting each component several times, then stacking those blocks together).
